export enum ResortLocation {
	PYEONGCHANG = 'PYEONGCHANG',
	JEONGSEON = 'JEONGSEON',
	HONGCHEON = 'HONGCHEON',
	CHUNCHEON = 'CHUNCHEON',
	WONJU = 'WONJU',
	HOENGSEONG = 'HOENGSEONG',
	YANGYANG = 'YANGYANG',
	GWANGJU_GYEONGGI = 'GWANGJU_GYEONGGI',
	ICHEON = 'ICHEON',
	POCHEON = 'POCHEON',
	MUJU = 'MUJU',
}

export enum ResortLevel {
	BEGINNER = 'BEGINNER',
	INTERMEDIATE = 'INTERMEDIATE',
	ADVANCED = 'ADVANCED',
	MIXED = 'MIXED',
}

export enum ResortFacilities {
	SKI_LIFT = 'SKI_LIFT',
	EQUIPMENT_RENTAL = 'EQUIPMENT_RENTAL',
	SKI_SCHOOL = 'SKI_SCHOOL',
	RESTAURANT = 'RESTAURANT',
	CAFE = 'CAFE',
	ACCOMMODATION = 'ACCOMMODATION',
	PARKING = 'PARKING',
	SHUTTLE_BUS = 'SHUTTLE_BUS',
	FIRST_AID = 'FIRST_AID',
	LOCKER = 'LOCKER',
	SLED_PARK = 'SLED_PARK',
}
